// <auto-generated />
namespace FGA.Congressus2.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IdentitySchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdentitySchema));
        
        string IMigrationMetadata.Id
        {
            get { return "201712201716462_IdentitySchema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
