//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA.Congressus2.Data.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Microsoft.AspNet.Identity.EntityFramework;
    using FGA.Congressus2.Entities;
    
    public partial class Congressus2Entities
    {
        public Congressus2Entities()
            : base("name=Congressus2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Archivos> Archivos { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<AreasCientificas> AreasCientificas { get; set; }
        public virtual DbSet<Conferencia> Conferencia { get; set; }
        public virtual DbSet<Eventos> Eventos { get; set; }
        public virtual DbSet<SeccionesEvento> SeccionesEvento { get; set; }
        public virtual DbSet<FormularioBecas> FormularioBecas { get; set; }
        public virtual DbSet<InscripcionConferencia> InscripcionConferencia { get; set; }
        public virtual DbSet<InscripcionEventos> InscripcionEventos { get; set; }
        public virtual DbSet<Evaluaciones> Evaluaciones { get; set; }
        public virtual DbSet<Paper> Paper { get; set; }
        public virtual DbSet<Revisiones> Revisiones { get; set; }
    }
}
