//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA.Congressus2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluaciones
    {
        public int EvaluacionId { get; set; }
        public int Calificacion { get; set; }
        public string PerfilId { get; set; }
        public int PaperId { get; set; }
        public string Comentario { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual Paper Paper { get; set; }
    }
}
