//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA.Congressus2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eventos()
        {
            this.AreasCientificas = new HashSet<AreasCientificas>();
            this.Conferencia = new HashSet<Conferencia>();
            this.FormularioBecas = new HashSet<FormularioBecas>();
            this.InscripcionEventos = new HashSet<InscripcionEventos>();
            this.Paper = new HashSet<Paper>();
            this.SeccionesEvento = new HashSet<SeccionesEvento>();
            this.Perfil = new HashSet<Perfil>();
        }
    
        public int EventoId { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaFinTrabajos { get; set; }
        public System.DateTime FechaFinInscripcion { get; set; }
        public System.DateTime FechaFinInscripcionTemprana { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Lugar { get; set; }
        public string Tema { get; set; }
        public string EmailContacto { get; set; }
        public string Direccion { get; set; }
        public bool HabilitarDescargaCertificados { get; set; }
        public Nullable<int> LogoId { get; set; }
        public string TextoBienvenida { get; set; }
    
        public virtual Archivos Archivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreasCientificas> AreasCientificas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conferencia> Conferencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormularioBecas> FormularioBecas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InscripcionEventos> InscripcionEventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paper> Paper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeccionesEvento> SeccionesEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perfil> Perfil { get; set; }
    }
}
