//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA.Congressus2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormularioBecas
    {
        public int FormularioBecaId { get; set; }
        public int EventoId { get; set; }
        public string NombreCompleto { get; set; }
        public string Domicilio { get; set; }
        public int CodigoPostal { get; set; }
        public string Localidad { get; set; }
        public string Provincia { get; set; }
        public string Pais { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public bool PresentaTrabajo { get; set; }
        public Nullable<int> AreaCientificaId { get; set; }
        public int CategoriaId { get; set; }
        public string Universidad { get; set; }
        public string Carrera { get; set; }
        public int PorcentajeCarrera { get; set; }
        public double PromedioParcial { get; set; }
        public string TituloGrado { get; set; }
        public int AñoGrado { get; set; }
        public string TituloPosgrado { get; set; }
        public int AñoPosgrado { get; set; }
        public int PorcentajePosgrado { get; set; }
        public string DirectorPosgrado { get; set; }
        public string LugarTrabajoPosgrado { get; set; }
        public string PosicionActual { get; set; }
        public string Puesto { get; set; }
        public int AsistenteId { get; set; }
    
        public virtual AreasCientificas AreasCientificas { get; set; }
        public virtual Eventos Eventos { get; set; }
    }
}
