//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA.Congressus2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InscripcionEventos
    {
        public int InscripcionEventoId { get; set; }
        public System.DateTime FechaInscripcion { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public bool Pago { get; set; }
        public Nullable<double> MontoPago { get; set; }
        public Nullable<int> EventoId { get; set; }
        public string PerfilId { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual Eventos Eventos { get; set; }
    }
}
