//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA.Congressus2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InscripcionConferencia
    {
        public int InscripcionConferenciaId { get; set; }
        public int ConferenciaId { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Conferencia Conferencia { get; set; }
    }
}
