//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA.Congressus2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revisiones
    {
        public int RevisionId { get; set; }
        public string Estado { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> ArchivoId { get; set; }
        public Nullable<int> PaperId { get; set; }
    
        public virtual Archivos Archivos { get; set; }
        public virtual Paper Paper { get; set; }
    }
}
