//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA.Congressus2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeccionesEvento
    {
        public int SeccionEventoId { get; set; }
        public string Nombre { get; set; }
        public string Titulo { get; set; }
        public string Cuerpo { get; set; }
        public Nullable<int> EventoId { get; set; }
    
        public virtual Eventos Eventos { get; set; }
    }
}
